services:
  product_postgres:
    image: postgres
    container_name: product_postgres
    read_only: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=153515
      - POSTGRES_DB=products
    expose:
      - "54322"
    ports:
      - "54322:54322"
    tmpfs:
      - /tmp
      - /run
      - /run/postgresql
    volumes:
      - product-volume:/var/lib/postgresql/data
    command: -p 54322

volumes:
  product-volume: